### ISSUE TITLE
support for python 3.9.4

### ISSUE THREAD

**Issue by CircleOnCircles** [doceme/py-spidev#121]
support for python 3.9.4

currently installation on ARMx32 failed

```
Using version ^3.5 for spidev

Updating dependencies
Resolving dependencies... (27.6s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing spidev (3.5): Failed

  EnvCommandError

  Command ['/home/pi/koihailoei/rpi/.venv/bin/pip', 'install', '--no-deps', '/home/pi/.cache/pypoetry/artifacts/29/61/7b/c8130ad199e91fd6977ae20845efb7a9207078a28d44d49128760ca32b/spidev-3.5.tar.gz'] errored with the following return code 1, and output: 
  Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
  Processing /home/pi/.cache/pypoetry/artifacts/29/61/7b/c8130ad199e91fd6977ae20845efb7a9207078a28d44d49128760ca32b/spidev-3.5.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /home/pi/koihailoei/rpi/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4cny1i2y/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4cny1i2y/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-
krsbyx16
           cwd: /tmp/pip-req-build-4cny1i2y/
      Complete output (13 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/home/pi/koihailoei/rpi/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 18, in <module>
          from setuptools.dist import Distribution
        File "/home/pi/koihailoei/rpi/.venv/lib/python3.9/site-packages/_virtualenv.py", line 89, in exec_module
          old(module)
        File "/home/pi/koihailoei/rpi/.venv/lib/python3.9/site-packages/setuptools/dist.py", line 32, in <module>
          from setuptools import windows_support
        File "/home/pi/koihailoei/rpi/.venv/lib/python3.9/site-packages/setuptools/windows_support.py", line 2, in <module>
          import ctypes
        File "/home/pi/.pyenv/versions/3.9.4/lib/python3.9/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      ----------------------------------------
  WARNING: Discarding file:///home/pi/.cache/pypoetry/artifacts/29/61/7b/c8130ad199e91fd6977ae20845efb7a9207078a28d44d49128760ca32b/spidev-3.5.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


```

**Comment by CircleOnCircles** [comment]
it is appeared to be that i forget to `apt install` essential packages of python
